apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql
  namespace: pfi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.234.0.240
    path: "/mysql"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mysql
  namespace: pfi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

